#!/bin/sh

# script to pull latest build from debbuilder
# take an answerfile as a parameter 1 
# take an installer command as a parameter 2 

dist="debian"
ver="6"
arch="i386"
latest=`ssh debbuilder 'cat ~/enterprise-dist/dists/LATEST'`

package="puppet-enterprise-$latest-$dist-$ver-$arch"

echo "Latest build: $latest"
echo "retrieving..."
scp debbuilder:~/enterprise-dist/dists/$package.tar.gz .
echo "done."
echo "retrieving answer file $1"
scp debbuilder:~/answer_files/$1 .

echo "unpacking..."
# if exists, remove
if [ -e ./"$package.tar.gz" ] ; then
  rm ./"$package.tar" >/dev/null 2>&1
  rm ./"$package" > /dev/null 2>&1
fi

# unpack
gzip -d ./"$package.tar.gz"
tar -xvf ./"$package.tar"

if [ -n "$2" ] ; then
	echo "running $2"
	if [ $2 = "install" ] ; then
	  ./$package/puppet-enterprise-installer -a $1
  elif [ $2 = "uninstall" ] ; then
    ./$package/puppet-enterprise-uninstaller -d -p -a $1
  fi
fi


