#!/bin/sh

# take an answerfile as a parameter 1 

echo "retrieving..."

if [ -n "$1" ] ; then
  echo "retrieving answer file $1"
  scp debbuilder:~/answer_files/$1 .
  if [ $? -ne 0 ] ; then
    exit 1
  fi
fi

